### ISSUE TITLE
Add current time to the variables

### ISSUE THREAD

**Issue by meza** [Aldaviva/WinampNowPlayingToFile#15]
Hey!

Amazing plugin, thanks for this! I often play mixes and it would be incredibly useful to be able to show the current time in the given track. Could this be added?

**Comment by Aldaviva** [comment]
Hi @meza,

Interesting suggestion! I don't know how to do that yet. Currently the plugin framework I'm using doesn't expose the current time. There may be a way to send a request from this plugin to Winamp to retrieve that information, but I will have to search around for it (the documentation isn't good).

I'll let you know if I find something.

**Comment by Aldaviva** [comment]
This [forum post](https://www.autohotkey.com/boards/viewtopic.php?p=242540&sid=a0ef8808a57d9bb17e814f595ea9973f#p242540) makes it sound like the magic `IPCCommand` lparam number for elapsed time might be `105`, which I believe because playback state is `104`.

**Comment by Aldaviva** [comment]
You can try replacing `WinampNowPlayingToFile.dll` with this development snapshot build and inserting something like `{{Elapsed:m\:ss}}` into your text template, or whatever other [timespan format](https://github.com/Aldaviva/WinampNowPlayingToFile#formatting) you like.

[WinampNowPlayingToFile.zip](https://github.com/Aldaviva/WinampNowPlayingToFile/files/13209569/WinampNowPlayingToFile.zip)

**Comment by Aldaviva** [comment]
Released in [2.2.0.0](https://github.com/Aldaviva/WinampNowPlayingToFile/releases/tag/2.2.0.0).
